#theme = "onedark"
theme = "dark_plus"

[editor]
line-number = "relative"
true-color = true
#mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
X = "extend_line_above"
